baseURL = 'https://rococo-figolla-41fc8e.netlify.app/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'form-builder'

disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"] # you will get a console error message without this

# [params]
#     theme = 'default'
#     sideMenuTheme = 'default'